/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.eventosGlobales.AdapterVentana;

//import AgenciaTurismo.vistas.windowHospedaje;

/**
 *
 * @author USER
 */
public class GuiAgenciaTurismo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgencia
     */
    public GuiAgenciaTurismo() {
        AdapterVentana adaptadorMain = new AdapterVentana();
        this.addWindowListener(adaptadorMain);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        ReguistroClientes = new javax.swing.JMenuItem();
        ReguistroClientes1 = new javax.swing.JMenuItem();
        MenuReserva = new javax.swing.JMenu();
        ReguistroReserva = new javax.swing.JMenuItem();
        BtnBuscarReserva = new javax.swing.JMenuItem();
        MenuHospedaje = new javax.swing.JMenu();
        ReguistroHospedaje = new javax.swing.JMenuItem();
        BusquedaConsultaReserva = new javax.swing.JMenuItem();
        MenuPaqueteTuristicos = new javax.swing.JMenu();
        ReguistroPaquetes = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCliente.setText("CLIENTE");

        ReguistroClientes.setText("Registrar");
        ReguistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroClientesActionPerformed(evt);
            }
        });
        MenuCliente.add(ReguistroClientes);

        ReguistroClientes1.setText("Buscar");
        ReguistroClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroClientes1ActionPerformed(evt);
            }
        });
        MenuCliente.add(ReguistroClientes1);

        jMenuBar1.add(MenuCliente);

        MenuReserva.setText("RESERVA");

        ReguistroReserva.setText("Registrar");
        ReguistroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroReservaActionPerformed(evt);
            }
        });
        MenuReserva.add(ReguistroReserva);

        BtnBuscarReserva.setText("Buscar");
        BtnBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarReservaActionPerformed(evt);
            }
        });
        MenuReserva.add(BtnBuscarReserva);

        jMenuBar1.add(MenuReserva);

        MenuHospedaje.setText("HOSPEDAJE");

        ReguistroHospedaje.setText("Registrar");
        ReguistroHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroHospedajeActionPerformed(evt);
            }
        });
        MenuHospedaje.add(ReguistroHospedaje);

        BusquedaConsultaReserva.setText("Buscar");
        BusquedaConsultaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaConsultaReservaActionPerformed(evt);
            }
        });
        MenuHospedaje.add(BusquedaConsultaReserva);

        jMenuBar1.add(MenuHospedaje);

        MenuPaqueteTuristicos.setText("PAQUETE TURISTICO");

        ReguistroPaquetes.setText("Registrar");
        ReguistroPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroPaquetesActionPerformed(evt);
            }
        });
        MenuPaqueteTuristicos.add(ReguistroPaquetes);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        MenuPaqueteTuristicos.add(Buscar);

        jMenuBar1.add(MenuPaqueteTuristicos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReguistroPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroPaquetesActionPerformed
        // TODO add your handling code here:
        RegistroPaquete reguistro = new RegistroPaquete();
        reguistro.setVisible(true);
    }//GEN-LAST:event_ReguistroPaquetesActionPerformed

    private void ReguistroHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroHospedajeActionPerformed
        // TODO add your handling code here:
        VentanaRegistro reguistroHospedaje = new VentanaRegistro();
        reguistroHospedaje.setVisible(true);
    }//GEN-LAST:event_ReguistroHospedajeActionPerformed

    private void ReguistroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroReservaActionPerformed
        // TODO add your handling code here:
        RegistroReserva reguistroReserva = new RegistroReserva();
        reguistroReserva.setVisible(true);
    }//GEN-LAST:event_ReguistroReservaActionPerformed

    private void ReguistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroClientesActionPerformed
        RegistroCliente reguistroCliente = new RegistroCliente();
        reguistroCliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReguistroClientesActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        VentanaConsultaPaquetes ventana = new VentanaConsultaPaquetes();
        ventana.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void BtnBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarReservaActionPerformed
        // TODO add your handling code here:
        VentanaConsultaReserva vent = new VentanaConsultaReserva();
        vent.setVisible(true);
    }//GEN-LAST:event_BtnBuscarReservaActionPerformed

    private void ReguistroClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroClientes1ActionPerformed
        VentanaConsultaCliente ventana = new VentanaConsultaCliente();
        ventana.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReguistroClientes1ActionPerformed

    private void BusquedaConsultaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaConsultaReservaActionPerformed
        VentanaconsultaHospedaje ventana = new VentanaconsultaHospedaje();
        ventana.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BusquedaConsultaReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAgenciaTurismo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnBuscarReserva;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem BusquedaConsultaReserva;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuHospedaje;
    private javax.swing.JMenu MenuPaqueteTuristicos;
    private javax.swing.JMenu MenuReserva;
    private javax.swing.JMenuItem ReguistroClientes;
    private javax.swing.JMenuItem ReguistroClientes1;
    private javax.swing.JMenuItem ReguistroHospedaje;
    private javax.swing.JMenuItem ReguistroPaquetes;
    private javax.swing.JMenuItem ReguistroReserva;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
