/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.modelos.HospedajeDAO;
import AgenciaTurismo.modelos.HospedajeDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author JOSE
 */
public class VentanaconsultaHospedaje extends javax.swing.JFrame {

    /**
     * Creates new form VentanaconsultaHospedaje
     */
    HospedajeDAO hospdao = new HospedajeDAO();
    ArrayList<HospedajeDTO> lista = hospdao.leer();
    
    public VentanaconsultaHospedaje() {
        initComponents();
        this.cmbNumeroHabitaciones.setVisible(false);
        this.bttNhabitaciones.setVisible(false);
        this.txtNombre.setVisible(false);
        this.bttNombre.setVisible(false);
        this.Tbregistro.setVisible(false);
        this.JPinfo.setVisible(false);
        this.JPanelTable.setVisible(false);
        this.cmbHospedaje.setVisible(false);
        DefaultComboBoxModel model = new DefaultComboBoxModel(lista.toArray());
        this.cmbHospedaje.setModel(model);
    }
    HospedajeDAO hospDAO = new HospedajeDAO();
    
    public void DatosTabla(String datos){
    ArrayList<HospedajeDTO> listaHab = hospDAO.buscarXHabitacion(Integer.parseInt(datos));
    System.out.println(listaHab.toString());
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
    String[] columnas = {"NOMBRE", "APELLIDO","# HABITACIONES", "PRECIO"};
    modelo.setColumnIdentifiers(columnas);
    for(HospedajeDTO hospe : listaHab){ // Only iterate through the filtered list
        Object[] hospedaje = new Object[]{hospe.getNombre(), hospe.getapellido(), hospe.getNumeroHabitaciones(), hospe.getprecioFinal()};
        modelo.addRow(hospedaje);
    }
    Tbregistro.setModel(modelo);
}
    
    public void informacion(String nombre){
        HospedajeDTO hospedaje = hospDAO.buscarXNombre(nombre);
        if (hospedaje == null) {
            txtInformacion.setText("no hay nadie registrado con ese nombre");
            return;
        }
        txtInformacion.setText(hospedaje.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbtexto = new javax.swing.JLabel();
        CmbBusquedad = new javax.swing.JComboBox<>();
        bttbuscar = new javax.swing.JButton();
        JPdatos = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        bttNhabitaciones = new javax.swing.JButton();
        cmbNumeroHabitaciones = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        bttNombre = new javax.swing.JButton();
        cmbHospedaje = new javax.swing.JComboBox<>();
        JPinfo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        JPanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbregistro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtexto.setText("SELECCIONE UN TIPO DE BUSQUEDAD");

        CmbBusquedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCION", "NOMBRE", "# HABITACIONES" }));

        bttbuscar.setText("Buscar");
        bttbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CmbBusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(bttbuscar))
                    .addComponent(lbtexto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtexto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbBusquedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttbuscar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        lbTitulo.setText(".");

        bttNhabitaciones.setText("Buscar");
        bttNhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNhabitacionesActionPerformed(evt);
            }
        });

        cmbNumeroHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "1", "2", "3", "4" }));

        bttNombre.setText("Buscar");
        bttNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNombreActionPerformed(evt);
            }
        });

        cmbHospedaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtInformacion.setColumns(20);
        txtInformacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtInformacion.setForeground(new java.awt.Color(0, 0, 0));
        txtInformacion.setRows(5);
        jScrollPane3.setViewportView(txtInformacion);

        javax.swing.GroupLayout JPinfoLayout = new javax.swing.GroupLayout(JPinfo);
        JPinfo.setLayout(JPinfoLayout);
        JPinfoLayout.setHorizontalGroup(
            JPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        JPinfoLayout.setVerticalGroup(
            JPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        Tbregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "APELLIDO", "# HABITACIONES", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(Tbregistro);

        javax.swing.GroupLayout JPanelTableLayout = new javax.swing.GroupLayout(JPanelTable);
        JPanelTable.setLayout(JPanelTableLayout);
        JPanelTableLayout.setHorizontalGroup(
            JPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        JPanelTableLayout.setVerticalGroup(
            JPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPdatosLayout = new javax.swing.GroupLayout(JPdatos);
        JPdatos.setLayout(JPdatosLayout);
        JPdatosLayout.setHorizontalGroup(
            JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPdatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(JPdatosLayout.createSequentialGroup()
                            .addComponent(cmbNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttNhabitaciones))
                        .addGroup(JPdatosLayout.createSequentialGroup()
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(bttNombre))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPdatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPdatosLayout.setVerticalGroup(
            JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPdatosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttNhabitaciones)
                    .addComponent(cmbNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttNombre))
                .addGap(18, 18, 18)
                .addComponent(cmbHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(JPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPdatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPdatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttbuscarActionPerformed
        // TODO add your handling code here:
        switch (this.CmbBusquedad.getSelectedItem().toString()) {
            case "SELECCION":
            this.lbTitulo.setText("");
            this.cmbNumeroHabitaciones.setVisible(false);
            this.bttNhabitaciones.setVisible(false);
            this.txtNombre.setVisible(false);
            this.bttNombre.setVisible(false);
            break;
            case "NOMBRE":
            this.lbTitulo.setText("Ingrese su nombre: ");
            this.bttNombre.setVisible(true);
            this.txtNombre.setVisible(true);

            this.cmbNumeroHabitaciones.setVisible(false);
            this.bttNhabitaciones.setVisible(false);
            this.txtInformacion.setVisible(true);
            this.JPanelTable.setVisible(false);

            break;
            case "# HABITACIONES":
            this.lbTitulo.setText("Seleccione el numero de habitaciones: ");

            this.cmbNumeroHabitaciones.setVisible(true);
            this.bttNhabitaciones.setVisible(true);

            this.Tbregistro.setVisible(true);

            this.bttNombre.setVisible(false);
            this.txtNombre.setVisible(false);
            this.txtInformacion.setVisible(false);
            this.JPanelTable.setVisible(true);
            this.JPinfo.setVisible(false);

            break;
            default:
            throw new AssertionError();
        }

    }//GEN-LAST:event_bttbuscarActionPerformed

    private void bttNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNombreActionPerformed
        // TODO add your handling code here:
        this.JPinfo.setVisible(true);
        informacion(this.txtNombre.getText());
    }//GEN-LAST:event_bttNombreActionPerformed

    private void bttNhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNhabitacionesActionPerformed
        // TODO add your handling code here:
        DatosTabla((String) this.cmbNumeroHabitaciones.getSelectedItem());
    }//GEN-LAST:event_bttNhabitacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaconsultaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaconsultaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaconsultaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaconsultaHospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaconsultaHospedaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbBusquedad;
    private javax.swing.JPanel JPanelTable;
    private javax.swing.JPanel JPdatos;
    private javax.swing.JPanel JPinfo;
    private javax.swing.JTable Tbregistro;
    private javax.swing.JButton bttNhabitaciones;
    private javax.swing.JButton bttNombre;
    private javax.swing.JButton bttbuscar;
    private javax.swing.JComboBox<String> cmbHospedaje;
    private javax.swing.JComboBox<String> cmbNumeroHabitaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbtexto;
    private javax.swing.JTextArea txtInformacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
