/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.modelos.ReservaDAO;
import AgenciaTurismo.modelos.ReservaDTO;
import java.util.ArrayList;

/**
 *
 * @author USER
 */
public class VentanaConsultaReserva extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaReserva
     */
    public VentanaConsultaReserva() {
        initComponents();
        this.jPanelComun1.setVisible(false);
        this.JPanelUnico.setVisible(false);
        this.jPanelUnico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleReserva = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkComun = new javax.swing.JCheckBox();
        chkUnico = new javax.swing.JCheckBox();
        btnTipoBusqueda = new javax.swing.JButton();
        jPanelUnico = new javax.swing.JPanel();
        txtBusquedaUnica = new javax.swing.JTextField();
        BotonSearchId = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInformacionUnico = new javax.swing.JTextArea();
        JPanelUnico = new javax.swing.JPanel();
        tipoBusqueda = new javax.swing.JLabel();
        jPanelComun = new javax.swing.JPanel();
        jPanelComun1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtBusquedaDia = new javax.swing.JTextField();
        BotonSearchDia1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaReservas = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CONSULTAR RESERVAS");

        buttonGroup1.add(chkComun);
        chkComun.setText("BusquedaComun");

        buttonGroup1.add(chkUnico);
        chkUnico.setText("Busqueda unico");

        btnTipoBusqueda.setText("BUSCAR");
        btnTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoBusquedaActionPerformed(evt);
            }
        });

        txtBusquedaUnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaUnicaActionPerformed(evt);
            }
        });
        txtBusquedaUnica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaUnicaKeyTyped(evt);
            }
        });

        BotonSearchId.setText("BUSCAR");
        BotonSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSearchIdActionPerformed(evt);
            }
        });

        jLabel4.setText("INGRESE ID");

        TxtInformacionUnico.setColumns(20);
        TxtInformacionUnico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TxtInformacionUnico.setRows(5);
        jScrollPane1.setViewportView(TxtInformacionUnico);

        javax.swing.GroupLayout jPanelUnicoLayout = new javax.swing.GroupLayout(jPanelUnico);
        jPanelUnico.setLayout(jPanelUnicoLayout);
        jPanelUnicoLayout.setHorizontalGroup(
            jPanelUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBusquedaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonSearchId)
                .addGap(43, 43, 43))
            .addGroup(jPanelUnicoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUnicoLayout.setVerticalGroup(
            jPanelUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUnicoLayout.createSequentialGroup()
                .addGroup(jPanelUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSearchId)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TitleReservaLayout = new javax.swing.GroupLayout(TitleReserva);
        TitleReserva.setLayout(TitleReservaLayout);
        TitleReservaLayout.setHorizontalGroup(
            TitleReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleReservaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(TitleReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TitleReservaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(TitleReservaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(TitleReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TitleReservaLayout.createSequentialGroup()
                                .addComponent(jPanelUnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(TitleReservaLayout.createSequentialGroup()
                                .addComponent(chkComun)
                                .addGap(18, 18, 18)
                                .addComponent(chkUnico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTipoBusqueda)
                                .addGap(22, 22, 22))))))
        );
        TitleReservaLayout.setVerticalGroup(
            TitleReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TitleReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkComun)
                    .addComponent(chkUnico)
                    .addComponent(btnTipoBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanelUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tipoBusqueda.setText(".");

        javax.swing.GroupLayout JPanelUnicoLayout = new javax.swing.GroupLayout(JPanelUnico);
        JPanelUnico.setLayout(JPanelUnicoLayout);
        JPanelUnicoLayout.setHorizontalGroup(
            JPanelUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUnicoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tipoBusqueda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelUnicoLayout.setVerticalGroup(
            JPanelUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUnicoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tipoBusqueda)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel3.setText("INGRESE EL DIA");

        TxtBusquedaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBusquedaDiaActionPerformed(evt);
            }
        });
        TxtBusquedaDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBusquedaDiaKeyTyped(evt);
            }
        });

        BotonSearchDia1.setText("BUSCAR");
        BotonSearchDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSearchDia1ActionPerformed(evt);
            }
        });

        TablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaReservas);

        javax.swing.GroupLayout jPanelComun1Layout = new javax.swing.GroupLayout(jPanelComun1);
        jPanelComun1.setLayout(jPanelComun1Layout);
        jPanelComun1Layout.setHorizontalGroup(
            jPanelComun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComun1Layout.createSequentialGroup()
                .addGroup(jPanelComun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComun1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBusquedaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(BotonSearchDia1))
                    .addGroup(jPanelComun1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelComun1Layout.setVerticalGroup(
            jPanelComun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComun1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComun1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtBusquedaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSearchDia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelComunLayout = new javax.swing.GroupLayout(jPanelComun);
        jPanelComun.setLayout(jPanelComunLayout);
        jPanelComunLayout.setHorizontalGroup(
            jPanelComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelComun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComunLayout.setVerticalGroup(
            jPanelComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComunLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelComun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelUnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPanelUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitleReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       public void cargarTabla(int datoComun) {
        ArrayList<ReservaDTO> listaComun = AccesodatosReserva.BusquedaDia(datoComun);
        System.out.println(listaComun.toString());
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        String[] columnas = {"ID", "CLIENTE", "PAQUETE"};
        modelo.setColumnIdentifiers(columnas);
        for (ReservaDTO reserva : listaComun) {
            Object[] reservaRow = new Object[]{reserva.getIdReserva(), reserva.getCliente().getCedula(),
                reserva.getPaqueteTuristico().getNombrePaquete()};
            modelo.addRow(reservaRow);
        }
        TablaReservas.setModel(modelo);
    }

       
    ReservaDAO AccesodatosReserva = new ReservaDAO();
    ReservaDTO reserva = null;

    private void BotonSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSearchIdActionPerformed
        // TODO add your handling code here:
        reserva = AccesodatosReserva.BusquedaID(this.txtBusquedaUnica.getText());
        if (reserva == null) {
            this.TxtInformacionUnico.setText("No hay ningun cliente reguistrado con esa cedula");
            return;
        }
        this.TxtInformacionUnico.setText(reserva.toString());
    }//GEN-LAST:event_BotonSearchIdActionPerformed

    private void TxtBusquedaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBusquedaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBusquedaDiaActionPerformed

    private void BotonSearchDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSearchDia1ActionPerformed
        // TODO add your handling code here:
        cargarTabla(Integer.parseInt(this.TxtBusquedaDia.getText()));
    }//GEN-LAST:event_BotonSearchDia1ActionPerformed

    private void btnTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoBusquedaActionPerformed
        // TODO add your handling code here:
        if (this.chkComun.isSelected()) {
            this.jPanelComun1.setVisible(true);
            this.jPanelUnico.setVisible(false);
        } else if (this.chkUnico.isSelected()) {
            this.jPanelUnico.setVisible(true);
            this.jPanelComun1.setVisible(false);
            this.JPanelUnico.setVisible(true);
        }
    }//GEN-LAST:event_btnTipoBusquedaActionPerformed

    private void txtBusquedaUnicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaUnicaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBusquedaUnicaKeyTyped

    private void TxtBusquedaDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBusquedaDiaKeyTyped

        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBusquedaDiaKeyTyped

    private void txtBusquedaUnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaUnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaUnicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSearchDia1;
    private javax.swing.JButton BotonSearchId;
    private javax.swing.JPanel JPanelUnico;
    private javax.swing.JTable TablaReservas;
    private javax.swing.JPanel TitleReserva;
    private javax.swing.JTextField TxtBusquedaDia;
    private javax.swing.JTextArea TxtInformacionUnico;
    private javax.swing.JButton btnTipoBusqueda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkComun;
    private javax.swing.JCheckBox chkUnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelComun;
    private javax.swing.JPanel jPanelComun1;
    private javax.swing.JPanel jPanelUnico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tipoBusqueda;
    private javax.swing.JTextField txtBusquedaUnica;
    // End of variables declaration//GEN-END:variables
}
