/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.modelos.HospedajeDAO;
import AgenciaTurismo.modelos.HospedajeDTO;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaHospedaje
     */
    public VentanaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbregistro = new javax.swing.JLabel();
        lbHoteles = new javax.swing.JLabel();
        CmbHoteles = new javax.swing.JComboBox<>();
        lbHabitaciones = new javax.swing.JLabel();
        SpnHabitaciones = new javax.swing.JSpinner();
        lbPersonas = new javax.swing.JLabel();
        BttAceptar = new javax.swing.JButton();
        BttCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbFecha1 = new javax.swing.JLabel();
        SpnFechaInicio = new javax.swing.JSpinner();
        SpnFechaFin = new javax.swing.JSpinner();
        txtNombre = new javax.swing.JTextField();
        lbnombre = new javax.swing.JLabel();
        lbapellido = new javax.swing.JLabel();
        Rbdos = new javax.swing.JRadioButton();
        Rbtres = new javax.swing.JRadioButton();
        Rbcuatro = new javax.swing.JRadioButton();
        Rbuno = new javax.swing.JRadioButton();
        txtApelllido = new javax.swing.JTextField();
        lbnPers = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbregistro.setFont(new java.awt.Font("Palatino Linotype", 0, 36)); // NOI18N
        lbregistro.setText("Reserva de Hotel");

        lbHoteles.setText("Hoteles Disponibles:");

        CmbHoteles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston Hotel", "Hotel Prices", "Wyndlam Garden" }));
        CmbHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbHotelesActionPerformed(evt);
            }
        });

        lbHabitaciones.setText("Numero de Habitaciones:");

        SpnHabitaciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        lbPersonas.setText("Numero de Personas: ");

        BttAceptar.setText("Aceptar");
        BttAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttAceptarActionPerformed(evt);
            }
        });

        BttCancelar.setText("Cancelar");
        BttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttCancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbFecha1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbFecha1.setText("Fecha de Inicio/Fin de la reserva:");

        SpnFechaInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1705548062034L), new java.util.Date(1706757660000L), java.util.Calendar.WEEK_OF_MONTH));

        SpnFechaFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1705548062034L), new java.util.Date(1706757660000L), java.util.Calendar.WEEK_OF_MONTH));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SpnFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SpnFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbFecha1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbFecha1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpnFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        lbnombre.setText("Nombre:");

        lbapellido.setText("Apellido:");

        buttonGroup1.add(Rbdos);
        Rbdos.setText("2");
        Rbdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbdosActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbtres);
        Rbtres.setText("3");
        Rbtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtresActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbcuatro);
        Rbcuatro.setText("4");
        Rbcuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbcuatroActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rbuno);
        Rbuno.setText("1");
        Rbuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbunoActionPerformed(evt);
            }
        });

        txtApelllido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApelllidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BttAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(BttCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbHabitaciones)
                        .addGap(18, 18, 18)
                        .addComponent(SpnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbHoteles)
                        .addGap(18, 18, 18)
                        .addComponent(CmbHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbapellido)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtApelllido))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbnombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbPersonas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rbuno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rbdos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rbtres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rbcuatro)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbnPers, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbapellido)
                    .addComponent(txtApelllido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoteles)
                    .addComponent(CmbHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHabitaciones)
                    .addComponent(SpnHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPersonas)
                    .addComponent(Rbdos)
                    .addComponent(Rbtres)
                    .addComponent(Rbcuatro)
                    .addComponent(Rbuno))
                .addGap(4, 4, 4)
                .addComponent(lbnPers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttAceptar)
                    .addComponent(BttCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttAceptarActionPerformed
        // TODO add your handling code here:
        try{
        HospedajeDTO hosp = new HospedajeDTO();
        String nombre = txtNombre.getText();
        if (nombre.isEmpty()) {
            throw new Exception("El nombre no puede estar vacio");
        }
        hosp.setNombre(nombre);
        String apellido = txtApelllido.getText();
        if (apellido.isEmpty()) {
            throw new Exception("El apellido no puede estar vacio");
        }
        hosp.setapellido(apellido);
        String hoteles = (String) CmbHoteles.getSelectedItem();
        if (hoteles == null || hoteles.isEmpty()) {
            throw new Exception("Debes seleccionar un hotel");
        }
        hosp.setHoteles(hoteles);
        String Nhabitacion = Integer.toString((Integer)SpnHabitaciones.getValue());
        if (Nhabitacion.equals("0")) {
            throw new Exception("elije una opcion que no sea 0");
        } else {
        hosp.setNumeroHabitaciones(Nhabitacion);
        }
        int Npersonas = 0;
        if(Rbuno.isSelected()){
            Npersonas=1;
        }else if(Rbdos.isSelected()){
            Npersonas=2;
        }else if(Rbtres.isSelected()){
            Npersonas=3;
        }else if(Rbcuatro.isSelected()){
            Npersonas=4;
        }
        if (Npersonas == 0) {
            throw new Exception("Debes seleccionar el número de personas");
        }
        hosp.setNumeroPersonas(Npersonas);
        Date Finicio = (Date) SpnFechaInicio.getValue();
        Date Ffin = (Date) SpnFechaFin.getValue();
         if (Finicio.after(Ffin)) {
            throw new Exception("La fecha de inicio no puede ser mayor a la fecha final");
         }
        hosp.setFechaInicio(Finicio);
        hosp.setFechaFinal(Ffin);
        
        JOptionPane.showMessageDialog(null,hosp.toString());
        
        HospedajeDAO dao = new HospedajeDAO();
        String res = dao.escribir(hosp);
        JOptionPane.showMessageDialog(null,
                res);
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
    }//GEN-LAST:event_BttAceptarActionPerformed

    private void BttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BttCancelarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)){
            evt.consume();
        }
                
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApelllidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelllidoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(!Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtApelllidoKeyTyped

    private void RbunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbunoActionPerformed
        // TODO add your handling code here:
        this.lbnPers.setText(" ");
    }//GEN-LAST:event_RbunoActionPerformed

    private void RbdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbdosActionPerformed
        // TODO add your handling code here:
        this.lbnPers.setText("descuento del 0.1%");
    }//GEN-LAST:event_RbdosActionPerformed

    private void RbtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtresActionPerformed
        // TODO add your handling code here:
        this.lbnPers.setText("descuento del 0.2%");
    }//GEN-LAST:event_RbtresActionPerformed

    private void RbcuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbcuatroActionPerformed
        // TODO add your handling code here:
         this.lbnPers.setText("descuento del 0.3%");
    }//GEN-LAST:event_RbcuatroActionPerformed

    private void CmbHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbHotelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttAceptar;
    private javax.swing.JButton BttCancelar;
    private javax.swing.JComboBox<String> CmbHoteles;
    private javax.swing.JRadioButton Rbcuatro;
    private javax.swing.JRadioButton Rbdos;
    private javax.swing.JRadioButton Rbtres;
    private javax.swing.JRadioButton Rbuno;
    private javax.swing.JSpinner SpnFechaFin;
    private javax.swing.JSpinner SpnFechaInicio;
    private javax.swing.JSpinner SpnHabitaciones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbFecha1;
    private javax.swing.JLabel lbHabitaciones;
    private javax.swing.JLabel lbHoteles;
    private javax.swing.JLabel lbPersonas;
    private javax.swing.JLabel lbapellido;
    private javax.swing.JLabel lbnPers;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbregistro;
    private javax.swing.JTextField txtApelllido;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
