//autor: COLOMA VERA JULIO 
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.modelos.PaqueteTuristicoDTO;
import AgenciaTurismo.modelos.PaqueteTuristicoDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author USER
 */
public class VentanaConsultaPaquetes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaPaquetes
     */
    PaqueteTuristicoDAO paqueteDao = new PaqueteTuristicoDAO();
    ArrayList<PaqueteTuristicoDTO> lista = paqueteDao.leer();

    public VentanaConsultaPaquetes() {
        initComponents();
        this.cmbTipoViaje.setVisible(false);
        this.btnBuscarComun.setVisible(false);
        this.btnBuscarUnico.setVisible(false);
        this.txtPaqueteBuscado.setVisible(false);
        this.data_Table.setVisible(false);
        this.cmbPaquetes.setVisible(false);
        this.jPanelComun.setVisible(false);
        this.jpanelInfoUnico.setVisible(false);

        DefaultComboBoxModel model = new DefaultComboBoxModel(lista.toArray());
        this.cmbPaquetes.setModel(model);
    }
    PaqueteTuristicoDAO paqueteDAO = new PaqueteTuristicoDAO();
ArrayList<PaqueteTuristicoDTO> listaComun=new ArrayList<>();
    public void cargarTabla(String datoComun) {
        listaComun.clear();
         listaComun= paqueteDAO.BusquedaTipoViaje(datoComun);
        System.out.println(listaComun.toString());
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        String[] columnas = {"ID", "NOMBRE", "DESTINO", "TIPOVIAJE", "PRECIO"};
        modelo.setColumnIdentifiers(columnas);
        for (PaqueteTuristicoDTO paquete : listaComun) {
            Object[] paqueteTuristico = new Object[]{paquete.getId(), paquete.getNombrePaquete(),
                paquete.getDestino(), paquete.getTipoViaje(), paquete.getPrecioFinal()};
            modelo.addRow(paqueteTuristico);
        }
        data_Table.setModel(modelo);
    }

    public void cargarInfoDatoUnico(String nombrePaquete) {
        PaqueteTuristicoDTO paquete = paqueteDAO.buscarXnombre(nombrePaquete);
        if (paquete == null) {
            txtInformacion.setText("EL PAQUETE NO SE ENCUENTRA REGUISTRADO");
            return;
        }
        txtInformacion.setText(paquete.MostrarDatos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBuscarParametro = new javax.swing.JButton();
        JPanelDatos = new javax.swing.JPanel();
        cmbTipoViaje = new javax.swing.JComboBox<>();
        btnBuscarComun = new javax.swing.JButton();
        txtPaqueteBuscado = new javax.swing.JTextField();
        btnBuscarUnico = new javax.swing.JButton();
        lblTituloBusqueda = new javax.swing.JLabel();
        cmbPaquetes = new javax.swing.JComboBox<>();
        jpanelInfoUnico = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        jPanelComun = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        data_Table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONE EL TIPO DE DATO DE BUSQUEDA :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--OPCIONES--", "DATO COMUN", "DATO UNICO" }));

        btnBuscarParametro.setText("Buscar");
        btnBuscarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarParametroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnBuscarParametro))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarParametro)))
        );

        cmbTipoViaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interprovincial", "Intraprovincial" }));

        btnBuscarComun.setText("Buscar");
        btnBuscarComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComunActionPerformed(evt);
            }
        });

        btnBuscarUnico.setText("Buscar");
        btnBuscarUnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUnicoActionPerformed(evt);
            }
        });

        lblTituloBusqueda.setText(".");

        cmbPaquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtInformacion.setColumns(20);
        txtInformacion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtInformacion.setForeground(new java.awt.Color(0, 0, 0));
        txtInformacion.setRows(5);
        jScrollPane3.setViewportView(txtInformacion);

        javax.swing.GroupLayout jpanelInfoUnicoLayout = new javax.swing.GroupLayout(jpanelInfoUnico);
        jpanelInfoUnico.setLayout(jpanelInfoUnicoLayout);
        jpanelInfoUnicoLayout.setHorizontalGroup(
            jpanelInfoUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelInfoUnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelInfoUnicoLayout.setVerticalGroup(
            jpanelInfoUnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        data_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CIUDAD"
            }
        ));
        jScrollPane2.setViewportView(data_Table);

        javax.swing.GroupLayout jPanelComunLayout = new javax.swing.GroupLayout(jPanelComun);
        jPanelComun.setLayout(jPanelComunLayout);
        jPanelComunLayout.setHorizontalGroup(
            jPanelComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComunLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelComunLayout.setVerticalGroup(
            jPanelComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelDatosLayout = new javax.swing.GroupLayout(JPanelDatos);
        JPanelDatos.setLayout(JPanelDatosLayout);
        JPanelDatosLayout.setHorizontalGroup(
            JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDatosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpanelInfoUnico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelDatosLayout.createSequentialGroup()
                            .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPaqueteBuscado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoViaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbPaquetes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79)
                            .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBuscarUnico)
                                .addComponent(btnBuscarComun)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelDatosLayout.setVerticalGroup(
            JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarComun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaqueteBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUnico))
                .addGap(18, 18, 18)
                .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelInfoUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelComun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(403, 403, 403))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarParametroActionPerformed
        switch (this.jComboBox1.getSelectedItem().toString()) {
            case "--OPCIONES--":
                this.lblTituloBusqueda.setText("");
                this.cmbTipoViaje.setVisible(false);
                this.btnBuscarComun.setVisible(false);
                this.btnBuscarUnico.setVisible(false);
                this.txtPaqueteBuscado.setVisible(false);
                break;
            case "DATO UNICO":
                this.lblTituloBusqueda.setText("INGRESE EL NOMBRE PAQUETE TURISTICO: ");
                btnBuscarUnico.setVisible(true);
                this.txtPaqueteBuscado.setVisible(true);

                this.cmbTipoViaje.setVisible(false);
                this.btnBuscarComun.setVisible(false);
                this.txtInformacion.setVisible(true);
                this.jPanelComun.setVisible(false);

                break;
            case "DATO COMUN":
                this.lblTituloBusqueda.setText("SELECCIONE EL TIPO DE VIAJE: ");

                this.cmbTipoViaje.setVisible(true);
                this.btnBuscarComun.setVisible(true);

                this.data_Table.setVisible(true);

                this.btnBuscarUnico.setVisible(false);
                this.txtPaqueteBuscado.setVisible(false);
                this.txtInformacion.setVisible(false);
                this.jPanelComun.setVisible(true);
                this.jpanelInfoUnico.setVisible(false);

                break;
            default:
                throw new AssertionError();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarParametroActionPerformed

    private void btnBuscarUnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUnicoActionPerformed
        // TODO add your handling code here:
        this.jpanelInfoUnico.setVisible(true);

        cargarInfoDatoUnico(this.txtPaqueteBuscado.getText());
    }//GEN-LAST:event_btnBuscarUnicoActionPerformed

    private void btnBuscarComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComunActionPerformed
        //         TODO add your handling code here:
        cargarTabla((String) this.cmbTipoViaje.getSelectedItem());
    }//GEN-LAST:event_btnBuscarComunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaPaquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelDatos;
    private javax.swing.JButton btnBuscarComun;
    private javax.swing.JButton btnBuscarParametro;
    private javax.swing.JButton btnBuscarUnico;
    private javax.swing.JComboBox<String> cmbPaquetes;
    private javax.swing.JComboBox<String> cmbTipoViaje;
    private javax.swing.JTable data_Table;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelComun;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanelInfoUnico;
    private javax.swing.JLabel lblTituloBusqueda;
    private javax.swing.JTextArea txtInformacion;
    private javax.swing.JTextField txtPaqueteBuscado;
    // End of variables declaration//GEN-END:variables
}
